spring:
  application:
    name: scah-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scah
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  output:
    ansi:
      enabled: always
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
server:
  port: 8080
logging:
  level:
    org.springframework.orm.jpa: debug
    org.springframework.transaction: debug
